spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

report-service:
      github:
        token: someTokenValue
        repository-api-url: https://api.github.com/repos/someRepositoryLocation
