spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  file:
    max-size: 5MB
logging.file: jrs.log

report-service:
      github:
        token: someTokenValue
        repository-api-url: https://api.github.com/repos/EmbedITCZ/jbehave-support
      zip:
        directory: ./target/reports/
        allowed-entry-extensions:
          - xml
          - js
          - xslt
          - log
          - png
      reports:
        folder: reports
        url: http://localhost:8080/${report-service.reports.folder}
      rest:
        username: user
        password: pass
      cleanup:
        cron: '0 0 6 * * *' # once per day at 6
        max-days: 30
